export const GET_CONFIG_REQUEST = "GET_CONFIG_REQUEST";
export const GET_CONFIG_SUCCESS = "GET_CONFIG_SUCCESS";
export const GET_CONFIG_FAIL = "GET_CONFIG_FAIL";
export const INITIAL_GAME_SESSION = "INITIAL_GAME_SESSION";
export const GET_QUESTION = "GET_QUESTION";
export const SET_STEP = "SET_STEP";

export const HANDLE_ANSWER_START = "HANDLE_ANSWER_START";
export const HANDLE_ANSWER_SUCCESS = "HANDLE_ANSWER_SUCCESS";
export const HANDLE_ANSWER_FAIL = "HANDLE_ANSWER_FAIL";

export const SET_END_GAME = "SET_END_GAME";
export const RESET_GAME = "RESET_GAME";
